Repository fossasia/susi_iOS, pull requests merged in 2019-02, with the labels that each got.

#495 App becomes unresponsive on clicking on area below the signup bu…
  Susi/Controllers/SignUpController/SignUpVCMethods.swift
Labels: bug-fix

#501 Fix:Alert Controller in logout cell in SettingVC
  Susi/Controllers/SettingsController/SettingsViewController.swift
  Susi/Helpers/ControllerConstants.swift
Labels: Under Review

#488 Feat: Share Skill Feature on Skill Detail View Controller
  Podfile
  Podfile.lock
  Susi.xcodeproj/project.pbxproj
  Susi/Controllers/SkillDetailViewController/SkillDetailVCMethods.swift
  Susi/Controllers/SkillDetailViewController/SkillDetailViewController.swift
  Susi/Helpers/ControllerConstants.swift
  Susi/Model/Client/Constants.swift
  Susi/Model/Skill.swift
Labels: Feature, Under Review

#503 Fixed memory issue
  Susi.xcworkspace/xcshareddata/xcschemes/Susi.xcscheme
  Susi/Controllers/ChatViewController/AudioRecorderDelegate.swift
  Susi/Controllers/ChatViewController/ChatVCMethods.swift
  Susi/Controllers/ChatViewController/ChatViewController.swift
  Susi/Controllers/SkillDetailViewController/SkillDetailVCMethods.swift
  Susi/Controllers/SkillDetailViewController/SkillDetailViewController.swift
  Susi/Controllers/SkillListingViewController/SkillListingVCMethods.swift
  Susi/Controllers/SkillListingViewController/SkillListingViewController.swift
  Susi/Custom Views/Skill Listing Cells/SkillListingCollectionView.swift
  Susi/Custom Views/Skill Listing Cells/SkillListingTableCell.swift
  Susi/Model/Skill.swift
  Susi/Supporting Files/AppDelegate.swift
Labels: Priority: High, bug-fix

#510 Fix: Reset Password Functionality
  Susi/Controllers/ResetPasswordController/ResetPasswordVCMethods.swift
Labels: bug-fix, ready

#511 Implemented Dismiss youtube video
  Susi/Controllers/PlayerViewController/PlayerViewController.swift
  Susi/Youtube-Player/VideoPlayerView.swift
Labels: enhancement, ready
